name: MMOCoreLevelAddon
version: '1.0-SNAPSHOT'
main: me.yiyi1234.mmocoreleveladdon.MMOCoreLevelAddon
api-version: 1.16

commands:
  MMOCoreLevelAddon:

permissions:
  test.op:
    default: op
depend:
  - MMOCore